name: Bump version
on:
  push:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    -
      name: checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    -
      name: Bump version and push tag
      uses: hennejg/github-tag-action@v4.4.0
      with:
        tag_prefix: ""
        default_bump: prerelease
        github_token: ${{ secrets.WORKFLOW_TOKEN }}
